#Prometheus Operator
prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

#Prometheus
prometheus:
  prometheusSpec:
    scrapeInterval: "30s"
    evaluationInterval: "30s"

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    retention: 15d
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        cpu: 500m
        memory: 1Gi

#  Alertmanager
alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

# Grafana
grafana:
  enabled: true

  adminPassword: ""
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: UTC
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  grafana.ini:
    analytics:
      check_for_updates: false
      reporting_enabled: false
    auth.anonymous:
      enabled: false
    server:
      root_url: "https://grafana.nurtrade.net"

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-2:447924746567:certificate/17856910-e6a2-457e-9eeb-574c0c3740da"
    hosts:
      - grafana.nurtrade.net
    path: /

# Node Exporter
nodeExporter:
  enabled: true

# Kube State Metrics
kubeStateMetrics:
  enabled: true

# Default scrape targets
kubeApiServer:
  enabled: true

kubeControllerManager:
  enabled: true

kubeScheduler:
  enabled: true

kubelet:
  enabled: true

kubeEtcd:
  enabled: true

coreDns:
  enabled: true
